# Generated by Django 4.2.13 on 2024-05-15 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MapName", models.CharField(max_length=255)),
                ("Raster", django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
