# Generated by Django 4.1 on 2024-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeningitisPredictionApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("articleTitle", models.CharField(max_length=255)),
                ("articleContent", models.TextField()),
                (
                    "articleImage",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Maps",
        ),
    ]
