# Generated by Django 4.1 on 2024-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeningitisPredictionApp", "0002_article_delete_maps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="articleImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="productionfiles/"
            ),
        ),
    ]
