# Generated by Django 4.1 on 2024-06-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeningitisPredictionApp", "0003_alter_article_articleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="articleImage",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
    ]
