# Generated by Django 4.1 on 2024-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeningitisPredictionApp", "0004_alter_article_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="articleSubtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
